apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  type: LoadBalancer
  selector:
    app: test-app
